%这个程序是一个空的界面模板
%设定并产生游戏界面大小及颜色
m=30;n=30;a0=10;
a=zeros(m,n)+a0;
%=========================== 
%build the GUI  
%define the plot button
plotbutton=uicontrol('style','pushbutton',... 
   'string','Run', ...
    'fontsize',12, ...
     'position',[100,400,50,20], ...
    'callback', 'run=1;');   %define the stop button 
 erasebutton=uicontrol('style','pushbutton',...
    'string','Stop', ...
    'fontsize',12, ...
     'position',[200,400,50,20], ...
    'callback','freeze=1;');   %define the Quit button  
quitbutton=uicontrol('style','pushbutton',...
    'string','Quit', ...
    'fontsize',12, ...
     'position',[300,400,50,20], ...
    'callback','stop=1;close;'); 
  number = uicontrol('style','text', ...
     'string','1', ...
    'fontsize',12, ...
     'position',[20,400,50,20]);  
   %==============================
imh = image(cat(3,a));
%  set(imh, 'erasemode', 'none')
 axis equal
 axis tight   %index definition for cell update
 stop= 0; %wait for a quit button push
 run = 0; %wait for a draw
 freeze = 0; %wait for a freeze 
 while (stop==0)     
     if (run==1)          %nearest neighbor sum          
     stepnumber = 1 + str2num(get(number,'string'));         
set(number,'string',num2str(stepnumber)) 
    end      
  if (freeze==1)      
   run = 0;       
  freeze = 0;   
  end    
  drawnow
 end
a1=ceil(m/2);b1=ceil(n/2);